name: Linux CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Install gtest
      uses: MarkusJx/googletest-installer@v1.1
    - uses: actions/checkout@v3
    - name: Run Test
      run: cd /home/runner/work/rpg-dialogues/rpg-dialogues && make test
