name: run_unit_tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gtest
      uses: MarkusJx/googletest-installer@v1.1
    - uses: actions/checkout@v1
    - name: run tests
      run: make test